name: nftm_dapp
description: A Flutter project which is providing to NFT creating.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  file_picker: ^5.3.3
  image_picker: ^1.0.2
  walletconnect_modal_flutter: ^2.1.5
  walletconnect_flutter_v2: ^2.1.4

  # STATE_MANAGEMENT
  flutter_riverpod: ^2.3.6
  riverpod: ^2.3.6

  # UI
  animated_text_kit: ^4.2.2

  # FIREBASE
  firebase_core: ^2.15.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
