name: nftm_dapp
description: A Flutter project which is providing to NFT creating.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.1
  bip39: ^1.0.6
  ed25519_hd_key: ^2.2.0
  hex: ^0.2.0
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  file_picker: ^5.3.3

  # STATE_MANAGEMENT
  flutter_riverpod: ^2.3.6
  riverpod: ^2.3.6

  # UI
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
