// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_apH5b5apo4p7FnSGtxcUUtQHEpxu3dI',
    appId: '1:68493765140:web:23e262b8a1fbf880c81501',
    messagingSenderId: '68493765140',
    projectId: 'nftm-24f9c',
    authDomain: 'nftm-24f9c.firebaseapp.com',
    storageBucket: 'nftm-24f9c.appspot.com',
    measurementId: 'G-FFY8EF817Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUrQdWn-7c2SZnWzQhbFubM994lID9Vb0',
    appId: '1:68493765140:android:d53dcf125328d0a1c81501',
    messagingSenderId: '68493765140',
    projectId: 'nftm-24f9c',
    storageBucket: 'nftm-24f9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg5TdeHAUTfz7NU7pUwMHgBXp96Rh8YhI',
    appId: '1:68493765140:ios:bb82f944f9882822c81501',
    messagingSenderId: '68493765140',
    projectId: 'nftm-24f9c',
    storageBucket: 'nftm-24f9c.appspot.com',
    iosClientId: '68493765140-r5cg9q655qa2bq0qm10hncmdkt8q7hl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.nftmdapp',
  );
}
